### ISSUE TITLE
TD() cannot use data frames as input

### ISSUE THREAD

**Issue by jorittmo** [jorittmo/singcar#4]

**Comment by annek7** [comment]
Hello, I am facing the same problem. Until 2 weeks ago or so, I analyzed lots of data with values out of data frames. As of today, TD() does not work with data.frames as input anymore. What can I do? I can't repeat my work, because I've written awfully lots of lines code (you wouldn't wanna know how many). I saved all those results in a table of course, but I cannot reproduce the calculation (also there is no time to change into another format from data.frame). It did work repeatedly before, actually, it never failed.
I'd be so glad if someone could give me advice. Thank you :)
Best, Anne

(Translation of error message: Error in stats::pt(stats, df = df) :
non-numeric argument for mathematical function)

![screenshot 2022-09-06 um 18 52 49](https://user-images.githubusercontent.com/112972388/188699265-3927322e-d134-43c5-8158-ad484036e4bb.jpg)
![screenshot 2022-09-06 um 18 53 42](https://user-images.githubusercontent.com/112972388/188699295-f4293acd-6a79-4a1d-90fd-634927a73895.jpg)

**Comment by jorittmo** [comment]
Hmm, I can't seem to reproduce your exact error messages but it looks like you are passing non numerical values to the `case` parameter. However, since I can't reproduce the exact errors there might be a deeper issue at play. What happens if you pass `TD_pat18_VLMT_Dg1_m1` wrapped in `as.numeric()` to the function? (i.e. `as.numeric(TD_pat18_VLMT_Dg1_m1)` )

**Comment by jorittmo** [comment]
This issue is actually about not being able to pass the scores of the control sample as a data frame, instead of a vector. So, we should perhaps start a new issue if it turns out there is a deeper problem.

**Comment by annek7** [comment]
Hi :) 
Thank you so much for your reply!
It works now when I wrap it in the "as.numeric()"!
But how could this change? I calculated over 40.600 values with the TD and BTD functions, with this code I had, working with data.frames, where the values are all numeric, there is just a simple result value in the "cell" of the data frame. When I started working with the TD and BTD functions, I checked a few times if the value is correct by just using the "print" command, and there was always just one numeric showing, for examle, like in this example: 7.
Now when I checked, there is a tibble, and more information than the numeric.
I didn't change any of the code since I first worked on it. 
Was there an update of the singcar package? Or maybe I installed too many packages I do not need for this calculation. My R studio version is 2022.07.1 and I'm on a MAC. I really do not know.

R EXAMPLE: 

TD_pat18_VLMT_Dg1_m1 <- VLMT_m1_age_group3_15_29[VLMT_m1_age_group3_15_29$pat =='18','VLMT_Su_Dg1.m1' ]

>  print(TD_pat18_VLMT_Dg1_m1)
  A tibble: 1 x 1
  VLMT_Su_Dg1.m1
           <dbl>
1              7

> class(TD_pat18_VLMT_Dg1_m1)
[1] "tbl_df"     "tbl"        "data.frame"

#### then with as.numeric:

> TD(case = as.numeric(TD_pat18_VLMT_Dg1_m1),
+    controls = 7.36,
+    sd = 2.08,
+    sample_size = 136,
+    alternative = "less",
+    conf_int = TRUE,
+    conf_level = 0.95,
+    conf_int_spec = 0.01,
+    na.rm = FALSE)

	Test of Deficit

data:  Case = 7.00, Controls (m = 7.36, sd = 2.08, n = 136)
t = -0.17244, df = 135, p-value = 0.4317
alternative hypothesis: true diff. between case and controls is less than 0
sample estimates:
    Std. case score (Z-CC), 95% CI [-0.34, 0.00] Proportion below case (%), 95% CI [36.59, 49.87] 
                                      -0.1730769                                       43.1673331 

It worked fine!!! Thank you! So if someone wants to reproduce my results (it's for my thesis),
he or she has to add as.numeric() to the function.

Here is an example of before (it worked on data frames), I found it on a slide of a presentation for my  seminar:

![screenshot 2022-09-07 um 16 48 06](https://user-images.githubusercontent.com/112972388/188908522-ac912046-d55a-4314-988c-0b691858912a.jpg)

It just irritates me why this changed? All the months before the functions were fine with data frames
and now not anymore.

But anyway, I really like to work on single case methodology with the TD and BTD functions.

And now I use this space to thank you for creating them :D !!!

Thank you very much for your help again and have a nice day!
All the best,
Anne

**Comment by annek7** [comment]
PS. or I just implement it earlier in t he process:
TD_pat25_VLMT_Dg1_m1 <- as.numeric(VLMT_m1_age_group3_15_29[VLMT_m1_age_group3_15_29$pat =='25','VLMT_Su_Dg1.m1'])
print(TD_pat25_VLMT_Dg1_m1)
TD(case = TD_pat25_VLMT_Dg1_m1,
   controls = 7.36,
   sd = 2.08,
   sample_size = 136,
   alternative = "less",
   conf_int = TRUE,
   conf_level = 0.95,
   conf_int_spec = 0.01,
   na.rm = FALSE)

Test of Deficit

data:  Case = 8.00, Controls (m = 7.36, sd = 2.08, n = 136)
t = 0.30657, df = 135, p-value = 0.6202
alternative hypothesis: true diff. between case and controls is less than 0
sample estimates:
     Std. case score (Z-CC), 95% CI [0.13, 0.48] Proportion below case (%), 95% CI [55.35, 68.41] 
                                       0.3076923                                       62.0177460 

For now I am just SO GLAD that it works, because my thesis is based on the values calculated the last weeks/months – and now it is reproducible!

**Comment by jorittmo** [comment]
A tibble is a data frame but from the tidyverse and it behaves a little bit differently from the base data frame, so perhaps you used some tidyverse preprocessing that you didn't use before which converted the data frame into a tibble and caused the error? However, you should be able to use a single value in a tibble as input so in the next update I will take care of this. Glad it worked out :)

**Comment by jorittmo** [comment]
With the new release 0.1.5 on CRAN this issue is now fixed :) (sorry it took so long)

**Comment by annek7** [comment]
Thank you!!
